### ISSUE TITLE
File Upload Vulnerability

### ISSUE THREAD

**Issue by unam4** [CleverStupidDog/yf-exam#1]
### Description

***yf-exam*** is a multi-role online training and examination system. The system integrates user management, role management, department management, question bank management, test question management, test question import and export, test management, online test, wrong question training and other functions, and the test process is perfect. ***@PostMapping("/common/api/file/upload")*** When this interface is uploaded, there is no restriction on the suffix of the uploaded file, resulting in any file upload.

### Vulnerability details

This interface accepts uploaded files, and then submits them to upload() for processing.

```
com.yf.exam.ability.upload.controller#upload()
```

![image](https://user-images.githubusercontent.com/66824584/216762346-b67d049d-1989-4e49-abbc-af520f7e974c.png)

Continue to follow up and come to the implementation class of the upload interface.

```
com.yf.exam.ability.upload.service.impl#upload()
```

![image](https://user-images.githubusercontent.com/66824584/216762352-d05a73fd-0b8b-4e0f-a1a3-dee7150bbe8a.png)
You can see that the incoming files are processed here, continue to follow up

```
com.yf.exam.ability.upload.utils#processPath()
```

![image](https://user-images.githubusercontent.com/66824584/216762363-54514438-a92b-4bd9-827f-227ab26dab19.png)

Then rename the incoming file

com.yf.exam.ability.upload.utils#renameFile()

![image](https://user-images.githubusercontent.com/66824584/216762374-b9a4e897-28dc-4bd4-becf-7b642662e902.png)

It can be seen that only the suffix name is intercepted, without filtering, it is directly spliced and put back。

![image](https://user-images.githubusercontent.com/66824584/216762391-f90382af-a582-4313-817f-066578499944.png)

Finally, return directly to the upload path.

### TEST

Upload file at routing point

![image](https://user-images.githubusercontent.com/66824584/216762435-7a751d4e-748b-4e76-a476-3e2ffc2fe28c.png)

It can be found that the upload was successful

![image](https://user-images.githubusercontent.com/66824584/216762441-457d4ec0-6e7d-4822-8e17-3f782de6ea96.png)

Try to access, you can find that the access is successful。

**Comment by CleverStupidDog** [comment]
Solved
