### ISSUE TITLE
fastjson 1.2.56  Deserialization Vulnerabilities

### ISSUE THREAD

**Issue by unam4** [CleverStupidDog/yf-exam#3]
![image](https://user-images.githubusercontent.com/66824584/217627120-eaada60c-4afc-4f17-9dc7-4a96ce38d526.png)
![image](https://user-images.githubusercontent.com/66824584/217627155-dc177546-4582-4e64-a692-a83d5b67e8ca.png)
![image](https://user-images.githubusercontent.com/66824584/217627293-b916ebf6-c799-4df9-b497-a60cfb0ed96e.png)
![image](https://user-images.githubusercontent.com/66824584/217627310-00682d38-fb6b-42a6-9caf-f726e8d3acd0.png)
![image](https://user-images.githubusercontent.com/66824584/217627334-e81417d5-5aad-40e2-b5b2-3bb829f5d2e2.png)
![image](https://user-images.githubusercontent.com/66824584/217627351-7081dca5-e9de-4b33-a0fe-e0ffb5297402.png)
![image](https://user-images.githubusercontent.com/66824584/217627376-ace002f3-6c7b-47b6-873e-f8653b0ca0cf.png)
![image](https://user-images.githubusercontent.com/66824584/217627401-13f53eed-5e0f-419e-ae6f-a5e02705d7a0.png)
![image](https://user-images.githubusercontent.com/66824584/217627445-61d27171-700e-4790-b0a8-0aa1f2c3d624.png)
![image](https://user-images.githubusercontent.com/66824584/217627472-0dfe71e4-90e6-4c0c-8d1e-66182c7271cc.png)
![image](https://user-images.githubusercontent.com/66824584/217627493-b5f05a65-34bf-4252-8ae5-1b2ad2fb9d67.png)

**Comment by CleverStupidDog** [comment]
upgraded fastjosn to 2.0.24
